name: iOS TestFlight (manual signing)

on:
  workflow_dispatch:   # запускать будем кнопкой из Actions

jobs:
  build-and-upload:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"   # можешь поставить latest-stable, но 16.2 уже точно есть

      # 1) Импорт дистрибутивного сертификата (.p12) из секретов
      - name: Import code signing certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      # 2) Установка App Store provisioning-профиля из секрета
      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 -D > ~/Library/MobileDevice/Provisioning\ Profiles/app.mobileprovision

      # 3) Сборка архива (Release, ручная подпись из настроек Xcode)
      - name: Build archive
        run: |
          xcodebuild \
             -scheme "ExpirationDateManager" \
             -configuration Release \
             -sdk iphoneos \
             -archivePath $PWD/build/App.xcarchive \
             -allowProvisioningUpdates \
             DEVELOPMENT_TEAM=Y65KPLRTB5 \
             PROVISIONING_PROFILE_SPECIFIER="WanderWalls" \
             CODE_SIGN_STYLE=Manual \
             PRODUCT_BUNDLE_IDENTIFIER=sw.iotalasab5.mules \
             clean archive
      # 4) Экспорт .ipa из архива
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build/export

      # 5) Загрузка .ipa в TestFlight
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: ${{ github.workspace }}/build/export/ExpirationDateManager.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
